import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    const {
      address,
      exterior,
      equipment,
      warranty,
      equipmentFlags,
      loadCalc,
    } = body;

    const pdf = await PDFDocument.create();
    const page = pdf.addPage([595, 842]); // A4 size
    const { width } = page.getSize();

    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

    let y = 800;

    const writeHeader = (text: string) => {
      page.drawText(text, {
        x: 40,
        y,
        size: 18,
        font: bold,
        color: rgb(0.2, 0.8, 0.4),
      });
      y -= 30;
    };

    const writeSectionTitle = (text: string) => {
      page.drawText(text, {
        x: 40,
        y,
        size: 14,
        font: bold,
      });
      y -= 18;
    };

    const writeLine = (label: string, value: unknown) => {
      const textValue =
        value === null || value === undefined ? "N/A" : String(value);
      page.drawText(`${label}: ${textValue}`, {
        x: 40,
        y,
        size: 10,
        font,
      });
      y -= 14;
    };

    // -------------------------
    // HEADER
    // -------------------------
    writeHeader("Dr HVAC – Job Summary Report");
    writeLine("Address", address);
    y -= 10;

    // -------------------------
    // EXTERIOR
    // -------------------------
    writeSectionTitle("Exterior Analysis");

    if (exterior) {
      writeLine("Stories", exterior.stories);
      writeLine("Siding", exterior.siding);
      writeLine("Windows", exterior.windows);
      writeLine("Gutters", exterior.gutters);
      writeLine("Condition", exterior.condition);
      writeLine("AI Confidence", exterior.confidence ?? "unknown");
    } else {
      writeLine("Exterior", "No exterior data available.");
    }

    y -= 10;

    // -------------------------
    // EQUIPMENT
    // -------------------------
    writeSectionTitle("Equipment Summary");

    if (equipment) {
      writeLine("Type", equipment.equipmentType);
      writeLine("Manufacturer", equipment.manufacturer);
      writeLine("Model Number", equipment.modelNumber);
      writeLine("Serial Number", equipment.serialNumber);
      writeLine("Input BTUH", equipment.inputBTUH);
      writeLine("Stages", equipment.stages);
      writeLine("AFUE", equipment.afue);
      writeLine("Vent Type", equipment.ventType);
    } else {
      writeLine("Equipment", "No equipment data available.");
    }

    y -= 10;

    // -------------------------
    // WARRANTY
    // -------------------------
    writeSectionTitle("Warranty Information");

    writeLine("Manufacture Year", warranty?.manufactureYear);
    writeLine("Approx Age", warranty?.approxAgeYears);
    writeLine("Warranty Status", warranty?.likelyWarrantyStatus);

    y -= 10;

    // -------------------------
    // FLAGS
    // -------------------------
    writeSectionTitle("Equipment Flags");

    if (equipmentFlags?.notes?.length > 0) {
      equipmentFlags.notes.forEach((note: string) => writeLine("- Note", note));
    } else {
      writeLine("Flags", "No flags detected.");
    }

    y -= 10;

    // -------------------------
    // LOAD CALC
    // -------------------------
    writeSectionTitle("Manual-J Lite Load Calculation");

    if (loadCalc) {
      writeLine("Sensible BTUH", loadCalc.sensibleBTUH);
      writeLine("Latent BTUH", loadCalc.latentBTUH);
      writeLine("Total BTUH", loadCalc.totalBTUH);
      writeLine(
        "Recommended Tonnage",
        `${loadCalc.recommendedTonnage} Tons`
      );
    } else {
      writeLine("Load Calc", "Load calc not completed.");
    }

    // -------------------------
    // FOOTER
    // -------------------------
    y = 40;
    page.drawText("Generated by Dr HVAC AI", {
      x: 40,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdf.save();

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": "attachment; filename=job-summary.pdf",
      },
    });
  } catch (err) {
    console.error("PDF Generation Error:", err);
    return NextResponse.json(
      { ok: false, error: "Failed to generate PDF." },
      { status: 500 }
    );
  }
}
